### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by shaktiman101** [Psarpei/Multi-Type-TD-TSR#9]
Hi, I was trying to run the model on the below image:
![2](https://user-images.githubusercontent.com/42404233/156556547-982d6cca-1b60-4f29-a8e2-6b557b3f3c6a.png)
in Colab with following command: 
`!python /content/Multi_Type_TD_TSR/scripts/tsr.py --folder=/content/images --type="partially_color_inv" --img_output=/content/img_output --xml_output=/content/xml_output`
But I was getting the below error:
`Traceback (most recent call last):
  File "/content/Multi_Type_TD_TSR/scripts/tsr.py", line 30, in <module>
    boxes, img_processed = type_dict[args.type].recognize_structure(img)
  File "/content/Multi_Type_TD_TSR/scripts/TSR/table_structure_recognition_all.py", line 208, in recognize_structure
    center = [int(row[index][j][0] + row[index][j][2] / 2) for j in range(len(row[index]))]
IndexError: list index out of range`

Not sure though I have provided the correct value of '_type_' flag over here.

**Comment by NBd-hub** [comment]
I have a same problem,could u solve it

**Comment by NBd-hub** [comment]
sir ,i solved this problem ,that is your wrong 'type'

**Comment by Syang111** [comment]
> sir ,i solved this problem ,that is your wrong 'type'
i meet the same question,how did you solve that?

**Comment by Davidchenyuhao** [comment]
> 

i also have the same problem, could u tell me what is the wrong 'type'

**Comment by oops-moment** [comment]
Was anyone able to figure out why does it gives list indexing out of Range ?
